/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as FertilityAssessmentRouteImport } from './routes/fertility-assessment'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConsultRouteImport } from './routes/consult'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicRegistrationPaymentRouteImport } from './routes/api/public/registration-payment'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const FertilityAssessmentRoute = FertilityAssessmentRouteImport.update({
  id: '/fertility-assessment',
  path: '/fertility-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultRoute = ConsultRouteImport.update({
  id: '/consult',
  path: '/consult',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegistrationPaymentRoute =
  ApiPublicRegistrationPaymentRouteImport.update({
    id: '/api/public/registration-payment',
    path: '/api/public/registration-payment',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/consult': typeof ConsultRoute
  '/contact': typeof ContactRoute
  '/fertility-assessment': typeof FertilityAssessmentRoute
  '/payment': typeof PaymentRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/public/registration-payment': typeof ApiPublicRegistrationPaymentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/consult': typeof ConsultRoute
  '/contact': typeof ContactRoute
  '/fertility-assessment': typeof FertilityAssessmentRoute
  '/payment': typeof PaymentRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/public/registration-payment': typeof ApiPublicRegistrationPaymentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/consult': typeof ConsultRoute
  '/contact': typeof ContactRoute
  '/fertility-assessment': typeof FertilityAssessmentRoute
  '/payment': typeof PaymentRoute
  '/programs': typeof ProgramsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/public/registration-payment': typeof ApiPublicRegistrationPaymentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/consult'
    | '/contact'
    | '/fertility-assessment'
    | '/payment'
    | '/programs'
    | '/sitemap.xml'
    | '/testimonials'
    | '/api/public/registration-payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/consult'
    | '/contact'
    | '/fertility-assessment'
    | '/payment'
    | '/programs'
    | '/sitemap.xml'
    | '/testimonials'
    | '/api/public/registration-payment'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/consult'
    | '/contact'
    | '/fertility-assessment'
    | '/payment'
    | '/programs'
    | '/sitemap.xml'
    | '/testimonials'
    | '/api/public/registration-payment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ConsultRoute: typeof ConsultRoute
  ContactRoute: typeof ContactRoute
  FertilityAssessmentRoute: typeof FertilityAssessmentRoute
  PaymentRoute: typeof PaymentRoute
  ProgramsRoute: typeof ProgramsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ApiPublicRegistrationPaymentRoute: typeof ApiPublicRegistrationPaymentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fertility-assessment': {
      id: '/fertility-assessment'
      path: '/fertility-assessment'
      fullPath: '/fertility-assessment'
      preLoaderRoute: typeof FertilityAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult': {
      id: '/consult'
      path: '/consult'
      fullPath: '/consult'
      preLoaderRoute: typeof ConsultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/registration-payment': {
      id: '/api/public/registration-payment'
      path: '/api/public/registration-payment'
      fullPath: '/api/public/registration-payment'
      preLoaderRoute: typeof ApiPublicRegistrationPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ConsultRoute: ConsultRoute,
  ContactRoute: ContactRoute,
  FertilityAssessmentRoute: FertilityAssessmentRoute,
  PaymentRoute: PaymentRoute,
  ProgramsRoute: ProgramsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  ApiPublicRegistrationPaymentRoute: ApiPublicRegistrationPaymentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
